version: "3"

volumes:
  data-volume:

services:
  app:
    image: akruglov/cosmicteam:latest
    restart: always
    ports:
      - "80:3000"
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - data-volume:/data/db
    restart: always